### ISSUE TITLE
Create FunBotCommandRouter module

### ISSUE THREAD

**Issue by b01001011** [funprog/funbot#14]
Since our project is not limited to single dice application, we need a certain form of command router.

> Slack -----> Web Server -> FunBotCommandRouter -> FunBotDice

For example,
- If the Slack send a request `/dice 2d6`, 
- the `FunBotCommandRouter` shall receive `dice 2d6`, 
- and it will send `2d6` to the DiceBot.
- The `FunBotCommandRouter` will route the message to `PaymentBot` if the command was `payment` instead of `dice`.

Definition of done:
- Check if the message received from the slack contains the command. (ie. dice)
- Create a test file
- Implement `FunBotCommandRouter`

**Comment by jwChung** [comment]
@kwoolytech PaymentBot이 나온 후에 고민하는 것이 어떨까요?

**Comment by b01001011** [comment]
Kinda YAGNI. :) Hey Captain, I agree with you. I also didn't expect to do it now. Btw, are you going to close this issue? I was thinking of tagging a label, namely `Backlog`, `Good to have` or `Later`.

**Comment by jwChung** [comment]
Wow, you have been remembering the principle YAGNI! You can close this issue. If needing to discuss for this issue, anyone can reopen. Thanks for suggesting the new label but I think that the new one can cause confusion. What if we create a new label carefully?

**Comment by b01001011** [comment]
Yeah, I do remember what you have taught me. :) For the label thing.. Sure, that makes sense. Let me close this for now.

**Comment by younggi** [comment]
I will keep YAGNI in mind. Thanks to learn it!
