### ISSUE TITLE
슬랙에 깃헙 훅 설정하기

### ISSUE THREAD

**Issue by myeesan** [funprog/funbot#19]
PR후 직접리뷰를 요청하는 대신, PR 또는 이슈가 생성 되었을 때 채널을 통해 알림을 받도록 연동

**Comment by myeesan** [comment]
@jwChung Issue, PR 연동을 위해서 승인 권한이 필요하네요. Collaborator 에 등록해주실 수 있나요?

**Comment by jwChung** [comment]
:ok:

**Comment by jwChung** [comment]
@myeesan 권한 부여해드렸습니다.

**Comment by myeesan** [comment]
테스트입니다.

**Comment by myeesan** [comment]
확인 되었습니다. 처음에 저장소가 안보여서 설정을 조금 건드렸는데("서드파티 앱 접근권한...") 문제는 없어 보입니다. ^^;
