### ISSUE TITLE
Merge 정책 결정

### ISSUE THREAD

**Issue by myeesan** [funprog/funbot#23]
머지 승인을 위한 정책을 마련했으면 합니다.
**컨벤션**
1. ACK 승인, NAK 비승인: 해외에서 사용하는 용어같습니다. ACK Acknowledge 같습니다.
2. Approved
3. 투표형식 +1
**점수**
두 명이상 승인 또는, 2점 이상 획득시

**Comment by jwChung** [comment]
저도 다음 주에 얘기해보려고 개인적으로 메모하고 있었습니다. github 에서 승인을 표시하는 도구가 있나요?

**Comment by myeesan** [comment]
서드파티 도구들이 있기는 한데, 보통은 +1 또는 lgtm (looks good to me) 로 나타내는 것 같아요. 
아니면 thumb up 아이콘을 사용하던지요.

**Comment by jwChung** [comment]
@myeesan 검색해보니 _PullApprove_ 이런 서비스가 있군요.

개인적으로는 눈으로 파악하지 않고 기계적으로 하는 것이 좋은데, 혼자 결정할 수 있는 문제는 아니군요.

**Comment by jwChung** [comment]
결정되었습니다.
