### ISSUE TITLE
Merge기준 README에 정리

### ISSUE THREAD

**Issue by jwChung** [funprog/funbot#28]

**Comment by jwChung** [comment]
- 승인을 +1으로 표기
- 아래 두 조건 모두를 만족할 때 머지
  -  승인이 3개 이상
  -  반대의견이 없는 경우
- reviewer를 지정할 수 있음 (@kwoolytech 이 방식)

**Comment by curry-ing** [comment]
머지를 하려면 코멘트를 눈으로 탐색하면서 +1, 혹은 -1을 찾아야 하기에 불편할 것 같아
이모티콘같은 것으로 깔끔하게 확인할 수 있는 방법이 없나 생각해봤는데 
PULL Request의 댓글들에는 이모티콘으로 리액션을 달 수 있는데 본문에는 불가능하군요. 

그래서 말인데, PR 올리시는 분이 맨 처음에 dummy로 머지 투표를 위한 댓글을 올리시면 
거기에다가 thumb up / thumb down 같은 이모티콘으로 투표하면 어떨까요?

**Comment by curry-ing** [comment]
# Agreed?

예를 들면 이와 같은 댓글을 맨 처음에 달면 이 댓글에 이모티콘을 다는 방식입니다.
내용 부분에다가 (지금 이 부분) PR에 대한 간단한 요약? 같은게 들어가도 좋을것 같네요

**Comment by b01001011** [comment]
# Agreed?

The idea sounds good to me. The only concern I had was if we able to see who pressed 👍  but it looks like we can. Please press 👍 if you like Sunghoon's idea.

**Comment by jwChung** [comment]
@masunghoon 님 의견 참 좋네요. @kwoolytech #29 에 바로 반영하는 것은 어떨까요? 그리고 하나 제안드리고 싶은 것이 있는데 지금 내용을 README.md문서 보다 CONTRIBUTION.md에 정리해주시겠습니까? CONTRIBUTION.md 이 더 잘어울린다고 생각되네요.(아래 링크 참고)

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by b01001011** [comment]
Sure thing! I will get it done when I get back to home.

**Comment by myeesan** [comment]
@masunghoon 참 깔끔한 방법 같습니다. 저도 찬성합니다.

**Comment by jwChung** [comment]
많은 분들이 @masunghoon 님 의견에 동의해주시고 @kwoolytech 님이 #32 를 작성해주셨습니다. 의견을 드리기 좀 늦은 감이 있지만 제가 잘못이해한 부분이 있었습니다.

@masunghoon 님이 말씀하시는 Agree? 라는 댓글이 필요할까라는 생각을 해봤습니다. 처음 댓글 만들 필요 없이 그냥 PR 첫 설명을 투표 대상으로 보면 안될까요? 

뒷북 죄송합니다. -_-;;;

**Comment by jwChung** [comment]
아 생각해보니 너무 뒤 늦은 의견이네요. 위 제 의견은 무시하시는게 좋겠네요.

**Comment by curry-ing** [comment]
@jwChung 아 전 PR요청할 때 전 description이 저리 달리는 줄 몰랐고 
그기에 이모지를 사용 가능한 지는 더더욱 몰랐습니다. 나쁘지 않을 것 같은데요?
댓글이나 디스크립션이나 같은 객체로 생성되나보네요

**Comment by jwChung** [comment]
@masunghoon : 너무 늦은 의견이니 @kwoolytech 님 판단에 맡기는 것이 어떨까요?  :)

**Comment by curry-ing** [comment]
뭔가 애매한 부분에 대한 판단을 미루는 것은 좀.....

좋습니다 ㅋ

**Comment by jwChung** [comment]
@masunghoon 그런 뜻은 아니었습니다. 의견이 너무 많아서 되려 @kwoolytech 님 작업에 지장을 주는 것 같아서요. 논의되어야할 것이 미뤄졌다면 추가작업으로 반영하면되지 않을까 생각합니다. :)

**Comment by b01001011** [comment]
Nah.. changing the script is easy peasy. Feel free to make an opinion. This is what code review is for. :) Looks like having 👍 on the description would make our life simple.

**Comment by myeesan** [comment]
close #28 이슈 닫아도 될 것 같습니다.

**Comment by myeesan** [comment]
Closes #28 이슈 닫아도 될 것 같습니다.

**Comment by jwChung** [comment]
@myeesan 직접 닫으셔도 됩니다 ㅎ
