### ISSUE TITLE
이슈 채택 방식 CONTRIBUTION.md에 작성

### ISSUE THREAD

**Issue by jwChung** [funprog/funbot#38]
제기된 이슈를 진행할 것인지 말것인지 결정이 필요합니다. @funprog/core 멤버들 논의 결과 +3 이 표기된 이슈를 채택하기로 했습니다. 이런 제반 사항을 CONTRIBUTION.md 문서에 기록하는 것이 필요합니다.

**Comment by myeesan** [comment]
#40 에서 머지되어 닫습니다 👍
